version: "3"

services:
    webserver:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html

    curl:
        image: curlimages/curl
        volumes:
            - ./scripts:/app
        entrypoint: sh
        environment:
            WEB_SERVER_ADDRESS: webserver
        working_dir: /app