version: "3"
services:
    webserver:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./src:/usr/share/nginx/html

    database:
        image: mariadb
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        env_file:
            - ./db.env
        # healthcheck:
        #     test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USER --password=$$MYSQL_ROOT_PASSWORD
        #     start_period: 5s
        #     interval: 5s
        #     timeout: 5s
        #     retries: 55

    data_load:
        image: mariadb
        volumes:
            - ./seed_database:/seed_database
        env_file:
            - ./db.env
        command: /seed_database/load-schema.sh

    client:
        image: mariadb
        env_file:
            - ./db.env
        command: /usr/bin/mysql -h db

# volumes:
#     dbdata:
#         external: true
